Add/link guide methods
developmentseed/safetag-web pull request #120
Opened 2020-10-23 00:13 UTC by LanesGood

Adds link to full method page from guide summary:
![image](https://user-images.githubusercontent.com/12634024/96942383-fc97db00-14a2-11eb-8a53-ab3a847db99e.png)

TBD: whether or not to include activity link too?

Closes #58.

2020-10-23 10:20 UTC, vgeorge requested changes
@LanesGood I believe we will need to change the button "<- Back to all methods"  in method layout to be a "back" action, instead of a link to all methods, in order to the user return to the guide builder.

2020-10-23 17:45 UTC, LanesGood commented
@vgeorge I've added in a conditional that changes "Back to all Methods" to "Back to Guide Builder" if the method has been linked to from the guide builder. The `prevPage` prop created [here](https://github.com/developmentseed/safetag-web/pull/120/files#diff-7e41b55d822aa943bc2cda20e04492611df849287790ff37ebbea22b2dc692deR248) accounts for users linking to methods from the guide builder once URL params are implemented in #102, and this should address some of the concerns of #60 for navigating to methods from the guide builder.

2020-10-26 14:58 UTC, necoline commented on src/pages/guide-builder.js
> +                            prevPath: window.location.pathname,
you should be able to replace all `window` with `props` since location is being passed through by default - it is also being used to access the query string

2020-10-26 15:53 UTC, LanesGood commented
@necoline thanks for the suggestion - I've used location from props, and modified the prop destructuring and validation for the guide builder

2020-10-26 15:57 UTC, necoline commented on src/components/layouts/method-layout.js
> +                    ? prevPage
```suggestion
                    ? prevPath
```

2020-10-26 15:57 UTC, necoline commented on src/pages/guide-builder.js
> +                            prevPage: location.href.replace(location.origin, ''),
Why not just use `prevPath`?

2020-10-26 15:57 UTC, necoline commented on src/pages/guide-builder.js
> +                            prevPage: location.href.replace(location.origin, ''),
```suggestion
```

2020-10-26 15:57 UTC, necoline commented on src/components/layouts/method-layout.js
> +  const { state: { prevPath, prevPage } = {} } = location
```suggestion
  const { state: { prevPath } = {} } = location
```

2020-10-26 17:06 UTC, LanesGood commented on src/pages/guide-builder.js
> +                            prevPage: location.href.replace(location.origin, ''),
@necoline the `location.pathname` only includes the URL path, not any hashes or params that follow the final slash. `.replace()` is used here to remove the base URL from the full href and set the previous page. This way, clicking "Back to Guide Builder" on the method page preserves any selected activities encoded in the URL params from the guide builder page, if that was the previous page.

2020-10-26 21:22 UTC, necoline commented on src/pages/guide-builder.js
> +                            prevPage: location.href.replace(location.origin, ''),
I see. In that case, I would recommend `location.pathname + location.search` to make the definition of `prevPage` immediately apparent. You also wouldn't need the catch that you added in.

2020-10-26 22:53 UTC, necoline approved these changes

2020-10-27 00:38 UTC, LanesGood commented on src/pages/guide-builder.js
> +                            prevPage: location.href.replace(location.origin, ''),
@necoline great idea; I hadn't seen the queryparam implementation prior to building this, and neglected to update with your use of `location.search`. Have updated this, tested build, and will merge in given your approval and successful checks.

2020-10-27 00:39 UTC, merged